### ISSUE TITLE
How to normalize depth maps?

### ISSUE THREAD

**Issue by MegumiOuO** [DengPingFan/BBS-Net#1]
Thanks for your work. You say BBS_dataset haven't been normalized, so i want to know how to normalize depth maps.

Besides, you say there are normalized depth maps in http://dpfan.net/d3netbenchmark/ . But the size of dataset in link of google and baidu are different. So, which one has normalized depth maps?

**Comment by DengPingFan** [comment]
> Thanks for your work. You say BBS_dataset haven't been normalized, so i want to know how to normalize depth maps.
> 
> Besides, you say there are normalized depth maps in http://dpfan.net/d3netbenchmark/ . But the size of dataset in link of google and baidu are different. So, which one has normalized depth maps?

You can just apply minmax function as normalization. 
Best,
